name: Lint

on:
  pull_request_target:

jobs:

  lint:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        flake8 addon/. --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Comment on PR
      uses: actions/github-script@v4
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            body: "This PR introduces flake8 errors"
          })
          