name: Lint diff

on:
  pull_request_target:

jobs:

  diff:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        git diff -U0 event.pull_request.base.ref...event.pull_request.head.ref -- addon/. > flake8.diff
        type flake8.diff | flake8 --diff --output-file=flake8.txt --tee
    - name: Comment on PR
      uses: actions/github-script@v4
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            body: "This PR introduces flake8 errors"
          })
          