name: Lint

on:
  pull_request_target:

  push:
  
jobs:

  lint:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 addon --exit-zero
    - name: Comment on PR
      uses: actions/github-script@v4
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            ...context.repo,
            issue_number: context.payload.pull_request.number,
            body: "This PR introduces flake8 errors"
          })
          