name: Locust summary

on: [ pull_request_target ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: |
          git remote add upstream https://github.com/nvdaes/placeMarkers.git
          git fetch upstream
          git branch base upstream/master
          git checkout base
          git pull
          git diff -U0 base...${{ github.event.pull_request.head.sha }} -- addon/. > flake8.diff
          type flake8.diff | flake8 --diff --output-file=flake8.txt --tee
          
          
      #- name: Generate Locust summary
        #uses: simiotics/locust-action@main
        #id: locust
        #with:
          #format: html-github
      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'test' # '${{ steps.locust.outputs.summary }}',
            })

