name: Test comment

on:
  [pull_request_target]

jobs:

  comment:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Comment on PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Testing'
          })
          