name: Test comment

on:
  pull_request_target:

jobs:
  comment:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        with:
          script: |
            github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: "Testing"
            })
